import { JobCreationQuestion } from '../../../../services/types/jobCreationSteps';

export const defaultQuestions: JobCreationQuestion[] = [
  {
    id: 'fallback-1',
    question: 'Do you have the license required for this position?',
    type: 'choice',
    subtype: 'single',
    required: true,
    allowMultiple: false,
    options: ['Yes', 'No'],
    isDefault: true,
    isActive: false,
    originalId: 1,
    questionTypeId: 1,
    questionSubTypeId: 2,
    questionSubTypeValueId: null
  },
  {
    id: 'fallback-2',
    question: 'What is your annual salary requirement?',
    type: 'text',
    subtype: 'number',
    required: true,
    allowMultiple: false,
    options: [],
    isDefault: true,
    isActive: false,
    originalId: 2,
    questionTypeId: 2,
    questionSubTypeId: 3,
    questionSubTypeValueId: 1
  },
  {
    id: 'fallback-3',
    question: 'What is your earliest available start date?',
    type: 'date',
    subtype: 'single',
    required: false,
    allowMultiple: false,
    options: [],
    isDefault: true,
    isActive: false,
    originalId: 3,
    questionTypeId: 3,
    questionSubTypeId: 5,
    questionSubTypeValueId: null
  },
  {
    id: 'fallback-4',
    question: 'If needed, are you willing to relocate for this role?',
    type: 'choice',
    subtype: 'single',
    required: true,
    allowMultiple: false,
    options: ['Yes', 'No'],
    isDefault: true,
    isActive: false,
    originalId: 4,
    questionTypeId: 1,
    questionSubTypeId: 2,
    questionSubTypeValueId: null
  },
  {
    id: 'fallback-5',
    question: 'Do you have a state(s) license required for this position?',
    type: 'choice',
    subtype: 'single',
    required: true,
    allowMultiple: false,
    options: ['Yes', 'No'],
    isDefault: true,
    isActive: false,
    originalId: 5,
    questionTypeId: 1,
    questionSubTypeId: 2,
    questionSubTypeValueId: null
  },
  {
    id: 'fallback-6',
    question: 'What state are you currently licensed in?',
    type: 'text',
    subtype: 'number',
    required: false,
    allowMultiple: false,
    options: [],
    isDefault: true,
    isActive: false,
    originalId: 6,
    questionTypeId: 2,
    questionSubTypeId: 3,
    questionSubTypeValueId: 1
  },
  {
    id: 'fallback-7',
    question: 'Do you have the required degree to apply for this position?',
    type: 'choice',
    subtype: 'single',
    required: false,
    allowMultiple: false,
    options: ['Yes', 'No'],
    isDefault: true,
    isActive: false,
    originalId: 7,
    questionTypeId: 1,
    questionSubTypeId: 2,
    questionSubTypeValueId: null
  }
];
