// Pre-built email templates for react-email-editor
export const emailTemplates = [
  {
    id: "welcome-template",
    name: "Welcome Email",
    category: "welcome" as const,
    thumbnail: "/images/templates/welcome-template.png",
    description: "Perfect for welcoming new subscribers",
    design: {
      counters: {
        u_column: 1,
        u_row: 1,
        u_content_text: 1,
        u_content_heading: 1,
        u_content_button: 1,
      },
      body: {
        id: "template_1",
        rows: [
          {
            id: "row_1",
            cells: [1],
            columns: [
              {
                id: "column_1",
                contents: [
                  {
                    id: "heading_1",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Welcome to Our Newsletter!",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "32px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                  {
                    id: "text_1",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Thank you for subscribing! We're excited to have you on board.",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "16px",
                      fontFamily: "arial,helvetica,sans-serif",
                    },
                  },
                  {
                    id: "button_1",
                    type: "button",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      href: {
                        name: "web",
                        values: {
                          href: "https://example.com",
                          target: "_blank",
                        },
                      },
                      buttonColors: {
                        color: "#FFFFFF",
                        backgroundColor: "#3182ce",
                        hoverColor: "#FFFFFF",
                        hoverBackgroundColor: "#2c5aa0",
                      },
                      size: {
                        autoWidth: true,
                        width: "100%",
                      },
                      fontSize: "16px",
                      textAlign: "center",
                      lineHeight: "120%",
                      padding: "12px 20px",
                      text: "Get Started",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "20px",
              anchor: "",
              hideDesktop: false,
            },
          },
        ],
        values: {
          popupPosition: "center",
          popupWidth: "600px",
          popupHeight: "auto",
          borderRadius: "10px",
          contentAlign: "center",
          contentVerticalAlign: "center",
          contentWidth: "600px",
          fontFamily: {
            label: "Arial",
            value: "arial,helvetica,sans-serif",
          },
          preheaderText: "",
          textColor: "#000000",
          backgroundColor: "#e7e7e7",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          linkStyle: {
            body: true,
            linkColor: "#0000ee",
            linkHoverColor: "#0000ee",
            linkUnderline: true,
            linkHoverUnderline: true,
          },
          popupBackgroundColor: "#FFFFFF",
          popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
          popupCloseButton_position: "top-right",
          popupCloseButton_backgroundColor: "#DDDDDD",
          popupCloseButton_iconColor: "#000000",
          popupCloseButton_borderRadius: "0px",
          popupCloseButton_margin: "0px",
          popupCloseButton_action: {
            name: "close_popup",
            values: {},
          },
        },
      },
      schemaVersion: 16,
    },
  },
  {
    id: "newsletter-template",
    name: "Newsletter",
    category: "newsletter" as const,
    thumbnail: "/images/templates/newsletter-template.png",
    description: "Great for regular newsletter updates",
    design: {
      counters: {
        u_column: 2,
        u_row: 2,
        u_content_text: 2,
        u_content_heading: 2,
        u_content_image: 1,
      },
      body: {
        id: "template_2",
        rows: [
          {
            id: "row_1",
            cells: [1],
            columns: [
              {
                id: "column_1",
                contents: [
                  {
                    id: "image_1",
                    type: "image",
                    values: {
                      containerPadding: "20px",
                      anchor: "",
                      src: {
                        url: "https://via.placeholder.com/600x200/3182ce/ffffff?text=Newsletter+Header",
                        width: 600,
                        height: 200,
                      },
                      textAlign: "center",
                      altText: "Newsletter Header",
                      action: {
                        name: "web",
                        values: {
                          href: "",
                          target: "_blank",
                        },
                      },
                    },
                  },
                  {
                    id: "heading_1",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Monthly Newsletter",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "28px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "0px",
              anchor: "",
              hideDesktop: false,
            },
          },
          {
            id: "row_2",
            cells: [1],
            columns: [
              {
                id: "column_2",
                contents: [
                  {
                    id: "heading_2",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "What's New This Month",
                      color: "#000000",
                      textAlign: "left",
                      fontSize: "22px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                  {
                    id: "text_1",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
                      color: "#000000",
                      textAlign: "left",
                      fontSize: "16px",
                      fontFamily: "arial,helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "text_2",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
                      color: "#000000",
                      textAlign: "left",
                      fontSize: "16px",
                      fontFamily: "arial,helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "20px",
              anchor: "",
              hideDesktop: false,
            },
          },
        ],
        values: {
          popupPosition: "center",
          popupWidth: "600px",
          popupHeight: "auto",
          borderRadius: "10px",
          contentAlign: "center",
          contentVerticalAlign: "center",
          contentWidth: "600px",
          fontFamily: {
            label: "Arial",
            value: "arial,helvetica,sans-serif",
          },
          preheaderText: "",
          textColor: "#000000",
          backgroundColor: "#e7e7e7",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          linkStyle: {
            body: true,
            linkColor: "#0000ee",
            linkHoverColor: "#0000ee",
            linkUnderline: true,
            linkHoverUnderline: true,
          },
          popupBackgroundColor: "#FFFFFF",
          popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
          popupCloseButton_position: "top-right",
          popupCloseButton_backgroundColor: "#DDDDDD",
          popupCloseButton_iconColor: "#000000",
          popupCloseButton_borderRadius: "0px",
          popupCloseButton_margin: "0px",
          popupCloseButton_action: {
            name: "close_popup",
            values: {},
          },
        },
      },
      schemaVersion: 16,
    },
  },
  {
    id: "product-template",
    name: "Product Update",
    category: "product" as const,
    thumbnail: "/images/templates/product-template.png",
    description: "Showcase your latest products or features",
    design: {
      counters: {
        u_column: 1,
        u_row: 1,
        u_content_text: 1,
        u_content_heading: 1,
        u_content_button: 2,
        u_content_image: 1,
      },
      body: {
        id: "template_3",
        rows: [
          {
            id: "row_1",
            cells: [1],
            columns: [
              {
                id: "column_1",
                contents: [
                  {
                    id: "heading_1",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "New Product Launch!",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "32px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                  {
                    id: "image_1",
                    type: "image",
                    values: {
                      containerPadding: "20px",
                      anchor: "",
                      src: {
                        url: "https://via.placeholder.com/400x300/f0f0f0/333333?text=Product+Image",
                        width: 400,
                        height: 300,
                      },
                      textAlign: "center",
                      altText: "Product Image",
                      action: {
                        name: "web",
                        values: {
                          href: "",
                          target: "_blank",
                        },
                      },
                    },
                  },
                  {
                    id: "text_1",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "We're excited to introduce our latest product that will revolutionize your workflow. Get early access now!",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "18px",
                      fontFamily: "arial,helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "button_1",
                    type: "button",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      href: {
                        name: "web",
                        values: {
                          href: "https://example.com/product",
                          target: "_blank",
                        },
                      },
                      buttonColors: {
                        color: "#FFFFFF",
                        backgroundColor: "#28a745",
                        hoverColor: "#FFFFFF",
                        hoverBackgroundColor: "#218838",
                      },
                      size: {
                        autoWidth: true,
                        width: "100%",
                      },
                      fontSize: "16px",
                      textAlign: "center",
                      lineHeight: "120%",
                      padding: "12px 24px",
                      text: "Learn More",
                    },
                  },
                  {
                    id: "button_2",
                    type: "button",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      href: {
                        name: "web",
                        values: {
                          href: "https://example.com/buy",
                          target: "_blank",
                        },
                      },
                      buttonColors: {
                        color: "#FFFFFF",
                        backgroundColor: "#dc3545",
                        hoverColor: "#FFFFFF",
                        hoverBackgroundColor: "#c82333",
                      },
                      size: {
                        autoWidth: true,
                        width: "100%",
                      },
                      fontSize: "16px",
                      textAlign: "center",
                      lineHeight: "120%",
                      padding: "12px 24px",
                      text: "Buy Now",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "20px",
              anchor: "",
              hideDesktop: false,
            },
          },
        ],
        values: {
          popupPosition: "center",
          popupWidth: "600px",
          popupHeight: "auto",
          borderRadius: "10px",
          contentAlign: "center",
          contentVerticalAlign: "center",
          contentWidth: "600px",
          fontFamily: {
            label: "Arial",
            value: "arial,helvetica,sans-serif",
          },
          preheaderText: "",
          textColor: "#000000",
          backgroundColor: "#e7e7e7",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          linkStyle: {
            body: true,
            linkColor: "#0000ee",
            linkHoverColor: "#0000ee",
            linkUnderline: true,
            linkHoverUnderline: true,
          },
          popupBackgroundColor: "#FFFFFF",
          popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
          popupCloseButton_position: "top-right",
          popupCloseButton_backgroundColor: "#DDDDDD",
          popupCloseButton_iconColor: "#000000",
          popupCloseButton_borderRadius: "0px",
          popupCloseButton_margin: "0px",
          popupCloseButton_action: {
            name: "close_popup",
            values: {},
          },
        },
      },
      schemaVersion: 16,
    },
  },
  {
    id: "macbook-pro-template",
    name: "MacBook Pro",
    category: "product" as const,
    thumbnail: "/images/templates/macbook-template.png",
    description: "Apple MacBook Pro style product showcase",
    design: {
      counters: {
        u_column: 13,
        u_row: 8,
        u_content_text: 24,
        u_content_image: 8,
        u_content_button: 2,
        u_content_divider: 1,
        u_content_heading: 3,
        u_content_menu: 1,
      },
      body: {
        id: "macbook_pro_template",
        rows: [
          {
            id: "row_header",
            cells: [1],
            columns: [
              {
                id: "column_header",
                contents: [
                  {
                    id: "apple_logo",
                    type: "image",
                    values: {
                      containerPadding: "10px 10px 0px",
                      src: {
                        url: "https://assets.unlayer.com/projects/139/1676495528722-apple_logo_circle_f5f5f7-000_2x.png",
                        width: 116,
                        height: 116,
                        maxWidth: "15%",
                      },
                      textAlign: "center",
                      altText: "Apple Logo",
                    },
                  },
                  {
                    id: "main_heading",
                    type: "heading",
                    values: {
                      containerPadding: "0px",
                      text: "MacBook Pro",
                      color: "#ffffff",
                      textAlign: "center",
                      fontSize: "48px",
                      fontFamily: "helvetica,sans-serif",
                      fontWeight: 400,
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "sub_heading",
                    type: "heading",
                    values: {
                      containerPadding: "0px",
                      text: "Mover. Maker. Boundary breaker.",
                      color: "#ffffff",
                      textAlign: "center",
                      fontSize: "28px",
                      fontFamily: "helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "price_text",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      text: "<p>From $1999 or $166.58/mo. for 12 mo.</p>",
                      color: "#ffffff",
                      textAlign: "center",
                      fontSize: "17px",
                      fontFamily: "helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                ],
                values: {
                  backgroundColor: "#000000",
                  padding: "0px",
                },
              },
            ],
            values: {
              backgroundColor: "#000000",
              padding: "0px",
            },
          },
          {
            id: "row_buttons",
            cells: [1, 1],
            columns: [
              {
                id: "column_buy",
                contents: [
                  {
                    id: "buy_button",
                    type: "button",
                    values: {
                      containerPadding: "10px",
                      text: "Buy",
                      color: "#FFFFFF",
                      backgroundColor: "#0071e3",
                      textAlign: "right",
                      fontSize: "17px",
                      fontFamily: "helvetica,sans-serif",
                      borderRadius: "25px",
                      padding: "10px 20px",
                      href: {
                        name: "web",
                        values: {
                          href: "#",
                          target: "_blank",
                        },
                      },
                    },
                  },
                ],
                values: {
                  backgroundColor: "#000000",
                },
              },
              {
                id: "column_learn",
                contents: [
                  {
                    id: "learn_text",
                    type: "text",
                    values: {
                      containerPadding: "20px",
                      text: "<p>Learn more</p>",
                      color: "#0071e3",
                      textAlign: "left",
                      fontSize: "17px",
                      fontFamily: "helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                ],
                values: {
                  backgroundColor: "#000000",
                },
              },
            ],
            values: {
              backgroundColor: "#000000",
              padding: "0px",
            },
          },
          {
            id: "row_hero",
            cells: [1],
            columns: [
              {
                id: "column_hero",
                contents: [
                  {
                    id: "hero_image",
                    type: "image",
                    values: {
                      containerPadding: "0px",
                      src: {
                        url: "https://assets.unlayer.com/projects/139/1676495949571-hero_2x.jpg",
                        width: 1424,
                        height: 880,
                      },
                      textAlign: "center",
                      altText: "MacBook Pro Hero",
                    },
                  },
                  {
                    id: "feature_1",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      text: "<p>Supercharged by M2 Pro and M2 Max.</p>",
                      color: "#9d9d9d",
                      textAlign: "center",
                      fontSize: "21px",
                      fontFamily: "helvetica,sans-serif",
                      fontWeight: 700,
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "feature_2",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      text: "<p>Up to 22 hours of battery life.</p>",
                      color: "#9d9d9d",
                      textAlign: "center",
                      fontSize: "21px",
                      fontFamily: "helvetica,sans-serif",
                      fontWeight: 700,
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "feature_3",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      text: "<p>Stunning Liquid Retina XDR display.</p>",
                      color: "#9d9d9d",
                      textAlign: "center",
                      fontSize: "21px",
                      fontFamily: "helvetica,sans-serif",
                      fontWeight: 700,
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "feature_4",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      text: "<p>All the ports you need and faster Wi-Fi 6E.</p>",
                      color: "#9d9d9d",
                      textAlign: "center",
                      fontSize: "21px",
                      fontFamily: "helvetica,sans-serif",
                      fontWeight: 700,
                      lineHeight: "140%",
                    },
                  },
                ],
                values: {
                  backgroundColor: "#000000",
                },
              },
            ],
            values: {
              backgroundColor: "#000000",
              padding: "15px 15px 70px",
            },
          },
          {
            id: "row_why_apple",
            cells: [1],
            columns: [
              {
                id: "column_why_apple",
                contents: [
                  {
                    id: "why_apple_heading",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      text: "Why Apple is the best place<br />to buy your new Mac.",
                      color: "#ffffff",
                      textAlign: "center",
                      fontSize: "32px",
                      fontFamily: "helvetica,sans-serif",
                      lineHeight: "120%",
                    },
                  },
                ],
                values: {
                  backgroundColor: "#1d1d1f",
                },
              },
            ],
            values: {
              backgroundColor: "#1d1d1f",
              padding: "50px",
            },
          },
        ],
        headers: [],
        footers: [],
        values: {
          contentWidth: 700,
          fontFamily: {
            label: "Helvetica",
            value: "helvetica,sans-serif",
          },
          textColor: "#ffffff",
          backgroundColor: "#000000",
          linkStyle: {
            linkColor: "#0071e3",
            linkHoverColor: "#0000ee",
            linkUnderline: true,
            linkHoverUnderline: true,
          },
          popupPosition: "center",
          popupWidth: "600px",
          popupHeight: "auto",
          borderRadius: "10px",
          contentAlign: "center",
          contentVerticalAlign: "center",
          preheaderText: "",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          popupBackgroundColor: "#FFFFFF",
          popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
          popupCloseButton_position: "top-right",
          popupCloseButton_backgroundColor: "#DDDDDD",
          popupCloseButton_iconColor: "#000000",
          popupCloseButton_borderRadius: "0px",
          popupCloseButton_margin: "0px",
          popupCloseButton_action: {
            name: "close_popup",
            values: {},
          },
        },
      },
      schemaVersion: 16,
    },
  },
];

export const getTemplateById = (id: string) => {
  return emailTemplates.find((template) => template.id === id);
};

export const getTemplatesByCategory = (category: string) => {
  return emailTemplates.filter((template) => template.category === category);
};
