// Pre-built email templates for react-email-editor
export const emailTemplates = [
  {
    id: "welcome-template",
    name: "Welcome Email",
    category: "welcome" as const,
    thumbnail: "/images/templates/welcome-template.png",
    description: "Perfect for welcoming new subscribers",
    design: {
      counters: {
        u_column: 1,
        u_row: 1,
        u_content_text: 1,
        u_content_heading: 1,
        u_content_button: 1,
      },
      body: {
        id: "template_1",
        rows: [
          {
            id: "row_1",
            cells: [1],
            columns: [
              {
                id: "column_1",
                contents: [
                  {
                    id: "heading_1",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Welcome to Our Newsletter!",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "32px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                  {
                    id: "text_1",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Thank you for subscribing! We're excited to have you on board.",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "16px",
                      fontFamily: "arial,helvetica,sans-serif",
                    },
                  },
                  {
                    id: "button_1",
                    type: "button",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      href: {
                        name: "web",
                        values: {
                          href: "https://example.com",
                          target: "_blank",
                        },
                      },
                      buttonColors: {
                        color: "#FFFFFF",
                        backgroundColor: "#3182ce",
                        hoverColor: "#FFFFFF",
                        hoverBackgroundColor: "#2c5aa0",
                      },
                      size: {
                        autoWidth: true,
                        width: "100%",
                      },
                      fontSize: "16px",
                      textAlign: "center",
                      lineHeight: "120%",
                      padding: "12px 20px",
                      text: "Get Started",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "20px",
              anchor: "",
              hideDesktop: false,
            },
          },
        ],
        values: {
          popupPosition: "center",
          popupWidth: "600px",
          popupHeight: "auto",
          borderRadius: "10px",
          contentAlign: "center",
          contentVerticalAlign: "center",
          contentWidth: "600px",
          fontFamily: {
            label: "Arial",
            value: "arial,helvetica,sans-serif",
          },
          preheaderText: "",
          textColor: "#000000",
          backgroundColor: "#e7e7e7",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          linkStyle: {
            body: true,
            linkColor: "#0000ee",
            linkHoverColor: "#0000ee",
            linkUnderline: true,
            linkHoverUnderline: true,
          },
          popupBackgroundColor: "#FFFFFF",
          popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
          popupCloseButton_position: "top-right",
          popupCloseButton_backgroundColor: "#DDDDDD",
          popupCloseButton_iconColor: "#000000",
          popupCloseButton_borderRadius: "0px",
          popupCloseButton_margin: "0px",
          popupCloseButton_action: {
            name: "close_popup",
            values: {},
          },
        },
      },
      schemaVersion: 16,
    },
  },
  {
    id: "newsletter-template",
    name: "Newsletter",
    category: "newsletter" as const,
    thumbnail: "/images/templates/newsletter-template.png",
    description: "Great for regular newsletter updates",
    design: {
      counters: {
        u_column: 2,
        u_row: 2,
        u_content_text: 2,
        u_content_heading: 2,
        u_content_image: 1,
      },
      body: {
        id: "template_2",
        rows: [
          {
            id: "row_1",
            cells: [1],
            columns: [
              {
                id: "column_1",
                contents: [
                  {
                    id: "image_1",
                    type: "image",
                    values: {
                      containerPadding: "20px",
                      anchor: "",
                      src: {
                        url: "https://via.placeholder.com/600x200/3182ce/ffffff?text=Newsletter+Header",
                        width: 600,
                        height: 200,
                      },
                      textAlign: "center",
                      altText: "Newsletter Header",
                      action: {
                        name: "web",
                        values: {
                          href: "",
                          target: "_blank",
                        },
                      },
                    },
                  },
                  {
                    id: "heading_1",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Monthly Newsletter",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "28px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "0px",
              anchor: "",
              hideDesktop: false,
            },
          },
          {
            id: "row_2",
            cells: [1],
            columns: [
              {
                id: "column_2",
                contents: [
                  {
                    id: "heading_2",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "What's New This Month",
                      color: "#000000",
                      textAlign: "left",
                      fontSize: "22px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                  {
                    id: "text_1",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
                      color: "#000000",
                      textAlign: "left",
                      fontSize: "16px",
                      fontFamily: "arial,helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "text_2",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
                      color: "#000000",
                      textAlign: "left",
                      fontSize: "16px",
                      fontFamily: "arial,helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "20px",
              anchor: "",
              hideDesktop: false,
            },
          },
        ],
        values: {
          popupPosition: "center",
          popupWidth: "600px",
          popupHeight: "auto",
          borderRadius: "10px",
          contentAlign: "center",
          contentVerticalAlign: "center",
          contentWidth: "600px",
          fontFamily: {
            label: "Arial",
            value: "arial,helvetica,sans-serif",
          },
          preheaderText: "",
          textColor: "#000000",
          backgroundColor: "#e7e7e7",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          linkStyle: {
            body: true,
            linkColor: "#0000ee",
            linkHoverColor: "#0000ee",
            linkUnderline: true,
            linkHoverUnderline: true,
          },
          popupBackgroundColor: "#FFFFFF",
          popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
          popupCloseButton_position: "top-right",
          popupCloseButton_backgroundColor: "#DDDDDD",
          popupCloseButton_iconColor: "#000000",
          popupCloseButton_borderRadius: "0px",
          popupCloseButton_margin: "0px",
          popupCloseButton_action: {
            name: "close_popup",
            values: {},
          },
        },
      },
      schemaVersion: 16,
    },
  },
  {
    id: "product-template",
    name: "Product Update",
    category: "product" as const,
    thumbnail: "/images/templates/product-template.png",
    description: "Showcase your latest products or features",
    design: {
      counters: {
        u_column: 1,
        u_row: 1,
        u_content_text: 1,
        u_content_heading: 1,
        u_content_button: 2,
        u_content_image: 1,
      },
      body: {
        id: "template_3",
        rows: [
          {
            id: "row_1",
            cells: [1],
            columns: [
              {
                id: "column_1",
                contents: [
                  {
                    id: "heading_1",
                    type: "heading",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "New Product Launch!",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "32px",
                      fontFamily: "arial,helvetica,sans-serif",
                      fontWeight: "bold",
                    },
                  },
                  {
                    id: "image_1",
                    type: "image",
                    values: {
                      containerPadding: "20px",
                      anchor: "",
                      src: {
                        url: "https://via.placeholder.com/400x300/f0f0f0/333333?text=Product+Image",
                        width: 400,
                        height: 300,
                      },
                      textAlign: "center",
                      altText: "Product Image",
                      action: {
                        name: "web",
                        values: {
                          href: "",
                          target: "_blank",
                        },
                      },
                    },
                  },
                  {
                    id: "text_1",
                    type: "text",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      text: "We're excited to introduce our latest product that will revolutionize your workflow. Get early access now!",
                      color: "#000000",
                      textAlign: "center",
                      fontSize: "18px",
                      fontFamily: "arial,helvetica,sans-serif",
                      lineHeight: "140%",
                    },
                  },
                  {
                    id: "button_1",
                    type: "button",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      href: {
                        name: "web",
                        values: {
                          href: "https://example.com/product",
                          target: "_blank",
                        },
                      },
                      buttonColors: {
                        color: "#FFFFFF",
                        backgroundColor: "#28a745",
                        hoverColor: "#FFFFFF",
                        hoverBackgroundColor: "#218838",
                      },
                      size: {
                        autoWidth: true,
                        width: "100%",
                      },
                      fontSize: "16px",
                      textAlign: "center",
                      lineHeight: "120%",
                      padding: "12px 24px",
                      text: "Learn More",
                    },
                  },
                  {
                    id: "button_2",
                    type: "button",
                    values: {
                      containerPadding: "10px",
                      anchor: "",
                      href: {
                        name: "web",
                        values: {
                          href: "https://example.com/buy",
                          target: "_blank",
                        },
                      },
                      buttonColors: {
                        color: "#FFFFFF",
                        backgroundColor: "#dc3545",
                        hoverColor: "#FFFFFF",
                        hoverBackgroundColor: "#c82333",
                      },
                      size: {
                        autoWidth: true,
                        width: "100%",
                      },
                      fontSize: "16px",
                      textAlign: "center",
                      lineHeight: "120%",
                      padding: "12px 24px",
                      text: "Buy Now",
                    },
                  },
                ],
                values: {
                  backgroundColor: "",
                  padding: "0px",
                  border: {},
                  borderRadius: "0px",
                },
              },
            ],
            values: {
              displayCondition: null,
              columns: false,
              backgroundColor: "",
              columnsBackgroundColor: "#ffffff",
              backgroundImage: {
                url: "",
                fullWidth: true,
                repeat: "no-repeat",
                size: "custom",
                position: "center",
              },
              padding: "20px",
              anchor: "",
              hideDesktop: false,
            },
          },
        ],
        values: {
          popupPosition: "center",
          popupWidth: "600px",
          popupHeight: "auto",
          borderRadius: "10px",
          contentAlign: "center",
          contentVerticalAlign: "center",
          contentWidth: "600px",
          fontFamily: {
            label: "Arial",
            value: "arial,helvetica,sans-serif",
          },
          preheaderText: "",
          textColor: "#000000",
          backgroundColor: "#e7e7e7",
          backgroundImage: {
            url: "",
            fullWidth: true,
            repeat: "no-repeat",
            size: "custom",
            position: "center",
          },
          linkStyle: {
            body: true,
            linkColor: "#0000ee",
            linkHoverColor: "#0000ee",
            linkUnderline: true,
            linkHoverUnderline: true,
          },
          popupBackgroundColor: "#FFFFFF",
          popupOverlay_backgroundColor: "rgba(0, 0, 0, 0.1)",
          popupCloseButton_position: "top-right",
          popupCloseButton_backgroundColor: "#DDDDDD",
          popupCloseButton_iconColor: "#000000",
          popupCloseButton_borderRadius: "0px",
          popupCloseButton_margin: "0px",
          popupCloseButton_action: {
            name: "close_popup",
            values: {},
          },
        },
      },
      schemaVersion: 16,
    },
  },
];

export const getTemplateById = (id: string) => {
  return emailTemplates.find((template) => template.id === id);
};

export const getTemplatesByCategory = (category: string) => {
  return emailTemplates.filter((template) => template.category === category);
};
